runtime: php55
api_version: 1

runtime_config:
  document_root: www.lazzyproperties.com

handlers:
# Serve images as static resources.
- url: /(.*\.(htm$|html$|css$|js$))
  static_files: \1

  upload: (.*\.(htm$|html$|css$|js$))
  application_readable: true

- url: /(.*\.(ico$|jpg$|png$|gif$))
  static_files: \1

  upload: (.*\.(ico$|jpg$|png$|gif$))
  application_readable: true

- url: /(.+)
  script: \1
  
- url: /c.zoocdn.com/static
  static_dir: static

- url: /.*
  script: index.php